### ISSUE TITLE
Cara Install Erapor SMK di Web Hosting

### ISSUE THREAD

**Issue by JunaidiSMK** [eraporsmk/eraporsmk#11]
Bagaimana Cara Install Erapor SMK di Web Hosting atau di sub domain situs sekolah. 
Terimakasih.

**Comment by gurumutant** [comment]
Anda bisa menggunakan tutorial berikut, dengan asumsi hosting berupa
layanan VPS (Virtual Private Server), dan bukan shared hosting:

https://seputar.erapor-smk.net/2019/10/22/tutorial-instalasi-erapor-smk-v5-0-0-di-linux/

**Comment by eraporsmk** [comment]
Close dulu, jika ada pertanyaan lagi silahkan open
