### ISSUE TITLE
tidak bisa sync rombongan belajar

### ISSUE THREAD

**Issue by skripsitik** [eraporsmk/eraporsmk#13]
selalu gagal mengambil data dari dapodik pada bagian rombongan belajar.

**Comment by skripsitik** [comment]
![image](https://user-images.githubusercontent.com/66456511/83837268-2df45200-a720-11ea-865f-4af6c5d192f9.png)

**Comment by eraporsmk** [comment]
Silahkan hubungi tim HD agar bisa di cek langsung
