### ISSUE TITLE
Kenapa Aplikasi erapor SMK tidak menggunakan database MYSQL saja

### ISSUE THREAD

**Issue by JunaidiSMK** [eraporsmk/eraporsmk#15]
Halo programmer Erapor SMK. 
Kenapa Erapor SMK tidak menggunakan database MYSQL saja biar kami pihak sekolah dapat menginstall di sub domain sekolah secara mudah,
karena banyak domain sekolah yang menggunakan Hosting biasa yang tidak support PGSQL. 
Dari hasil Googling, PGSQL dapat di install di VPS hosting atau Cloud hosting dengan harga sewa yang lumayan mahal.
Alternatif yang kami terapkan selama ini adalah Erapor SMK kami install di komputer sebagai server  di Sekolah  dengan Ram 8 GB lalu kami online kan komputer tersebut menggunakan no-ip atau juga Ip publik statis. 
Kendala yang kami hadapi adalah dalam 1 minggu komputer server harus di restart,  jika tidak maka akan offline, dan juga seringnya putus hubungan listrik PLN.

Kekurangan lain dari server yang kami install erepor smk di sekolah adalah servernya tidak selalu di onlinekan secara terus menerus,  komputer server hanya akan dionlinekan 1 bulan menjelang pembagian rapor supaya guru dapat mengisi nilai.
Hal ini menjadi kendala bagi kami guru yang ingin mengisi nilai di awal2 semester atau setiap selesai KD yang kami berikan ataupun setiap tugas harian yang kami berikan ke siswa. 

Saran saya kedepan semoga erapor smk versi 5.x.x dibuat dalam versi MYSQL database seperti aplikasi2 berbasis web populer lainnya yang banyak menggunakan MYSQL database. 

Apalah artinya sebuah aplikasi jika tidak dapat dipergunakan secara maksimal. 

Mohon maaf atas saran ini,  
Terimakasih.

Ttd
Junaidi, ST
junaidimkasem [at] gmail.com

**Comment by eraporsmk** [comment]
Terima kasih atas masukannya bapak @gacoksa.
Di versi awal rilis terdahulu, aplikasi eRapor SMK sudah menggunakan database MySQL, seiring berjalannya waktu, ukuran database semakin membengkak dan membuat aplikasi berjalan dengan lambat karena banyaknya data yang harus disimpan di database.
Oleh karena itu sejak versi 4.0.0 aplikasi eRapor SMK beralih menggunakan database PostgreSQL dengan tujuan memaksimalkan kinerja aplikasi dengan kondisi ukuran database yang cukup besar.

Mengenai penggunaan hosting, memang ada benarnya bahwa tidak semua penyedia hosting memberikan layanan PostgreSQL, namun tidak semua.
Bapak bisa mencoba Googling dengan menggunakan kata kunci "shared hosting postgresql", maka Google akan menampilkan pilihan-pilihan yang tersedia, baik hosting lokal maupun internasional.

Jika bapak mengalami kesulitan saat instalasi atau pengaturan server/aplikasi, silahkan menghubugi teman-teman Team Helpdesk.

Sekali lagi kami sampaikan terima kasih buat bapak Junaidi, ST

**Comment by simpanID** [comment]
> Halo programmer Erapor SMK.
> Kenapa Erapor SMK tidak menggunakan database MYSQL saja biar kami pihak sekolah dapat menginstall di sub domain sekolah secara mudah,
> karena banyak domain sekolah yang menggunakan Hosting biasa yang tidak support PGSQL.
> Dari hasil Googling, PGSQL dapat di install di VPS hosting atau Cloud hosting dengan harga sewa yang lumayan mahal.
> Alternatif yang kami terapkan selama ini adalah Erapor SMK kami install di komputer sebagai server di Sekolah dengan Ram 8 GB lalu kami online kan komputer tersebut menggunakan no-ip atau juga Ip publik statis.
> Kendala yang kami hadapi adalah dalam 1 minggu komputer server harus di restart, jika tidak maka akan offline, dan juga seringnya putus hubungan listrik PLN.
> 
> Kekurangan lain dari server yang kami install erepor smk di sekolah adalah servernya tidak selalu di onlinekan secara terus menerus, komputer server hanya akan dionlinekan 1 bulan menjelang pembagian rapor supaya guru dapat mengisi nilai.
> Hal ini menjadi kendala bagi kami guru yang ingin mengisi nilai di awal2 semester atau setiap selesai KD yang kami berikan ataupun setiap tugas harian yang kami berikan ke siswa.
> 
> Saran saya kedepan semoga erapor smk versi 5.x.x dibuat dalam versi MYSQL database seperti aplikasi2 berbasis web populer lainnya yang banyak menggunakan MYSQL database.
> 
> Apalah artinya sebuah aplikasi jika tidak dapat dipergunakan secara maksimal.
> 
> Mohon maaf atas saran ini,
> Terimakasih.
> 
> Ttd
> Junaidi, ST
> junaidimkasem [at] gmail.com

Untuk shared hosting yang support postgresql ada kok, coba cek di https://sansekertaindonesia.co.id disana ada subscribe tentang aplikasi untuk mengonline kan erapor dan shared hosting yang sudah support pgsql.. semoga membantu.

**Comment by satriazoro** [comment]
halo semua :)
saya punya masalah ketika membackup erapot ke komputer yang berbeda poto guru dan logo yang sebelumnya ada jadi menghilang apa ada pengaturan yang harus saya rubah ?

**Comment by xeizer** [comment]
then again... semoga sekolah bisa nabung untuk VPS
