### ISSUE TITLE
Migrasi Database e-rapor smk ke MariaDB

### ISSUE THREAD

**Issue by maspurmikrotiker** [eraporsmk/eraporsmk#17]
Tim pengembang e-raport yg kami hormati dan kami banggakan, 
Kapan database eraport migrasi ke MariaDB?? 
Tidak ada alasan untuk tidak pakai MariaDB karena ...MariaDB merupakan database terpopuler dan digunakan di hosting seluruh dunia ..postgresql tidak tersedia di layanan hosting. Mariadb mampu menangani database yg besar, Mariadb digunakan oleh Google, Facebook dan perusahaan start-up kelas dunia. 

Pengguna mysql lebih mudah beradaptasi ke MariaDB karena memiliki banyak kesamaan dalam synyax. 

Atau opsi 2 :
Buatkan e-raport versi MariaDB, 

Dengan begini tidak ada sekolah yg kesulitan dalam implementasi e-raport di lingkungan sekolah. 

Terima kasih....

**Comment by xeizer** [comment]
gak sih . untuk data besar, dan data berupa statistik, apalagi berisi dengan angka(banyak angka), menurut saya memang lebih cocok Postgres ketimbang MariaDB

**Comment by maspurmikrotiker** [comment]
Apakah ini bermaksud database eraport lebih besar dari databasenya google? hehehe becanda pak... 🙂
Sekedar info, google aja pakai MariaDB loh... 
Sumber:
https://www.babastudio.com/blog/google-meninggalkan-oracle-mysql-untuk-mariadb

**Comment by eraporsmk** [comment]
tidak semua aplikasi harus sama dengan google... hehehe... becanda pak :)
