### ISSUE TITLE
Koneksi aplikasi Erapor SMK ke firebase dan google spreadsheet.

### ISSUE THREAD

**Issue by JunaidiSMK** [eraporsmk/eraporsmk#18]
Dear Master.
Terimakasih atas aplikasi erapor smk, sangat mantap.
Saya punya saran bagaimana kedepannya kami dapat menginstall aplikasi erapor di server hosting dan database yang digunakan yaitu database punya google yaitu: firebase.
Dan firebase juga terkoneksi ke Spreadsheet.

Mohon maaf, mungkin saran saya ini terlalu berlebihan atau tidak masuk akal.
Terima kasih.

Ttd
Junaidi.

**Comment by eraporsmk** [comment]
Untuk saat ini pemakaian aplikasi e-Rapor SMK hanya menggunakan engine database PostgreSQL.
Jika ingin mengganti dengan engine database lainnya, sangat dipersilahkan untuk dikembangkan lagi sesuai kebutuhan...
Terima kasih.
