### ISSUE TITLE
Usulan untuk release cycle melalui git

### ISSUE THREAD

**Issue by dbrw** [eraporsmk/eraporsmk#2]
Hari ini wasek akademik sekolah kami melaporkan tidak bisa update, ternyata ada masalah tentang folder updates yang tidak ada.

Setelah masalah folder diatasi dan update berhasil berjalan, kami mendapat eror layar putih. Setelah saya selidiki lewat log, ternyata masalah cache composer yang tidak terupdate setelah proses update aplikasi.

Untuk memastikan folder diciptakan dan cache terupdate dengan baik, apakah tidak lebih mudah jika update dilakukan melalui repositori ini?

Mungkin logic update bisa disimpan dalam console command lewat artisan yang dapat dipanggil baik melalui web UI maupun console.

Mohon maaf jika masukkan saya kurang sesuai.

**Comment by eraporsmk** [comment]
@dbrw terima kasih banyak atas masukannya, untuk update dari 5.0.7 ke 5.0.8 kita akan memakai git
