### ISSUE TITLE
Koneksi ke server postgres ditolak.

### ISSUE THREAD

**Issue by matthelosh** [eraporsmk/eraporsmk#21]
Saya sudah melakukan pull ke lokal. Muncul error 👍 
Illuminate \ Database \ QueryException (7)
SQLSTATE[08006] [7] could not connect to server: Connection refused (0x0000274D/10061) Is the server running on host "localhost" (::1) and accepting TCP/IP connections on port 58154? could not connect to server: Connection refused (0x0000274D/10061) Is the server running on host "localhost" (127.0.0.1) and accepting TCP/IP connections on port 58154? (SQL: select * from "users" where "user_id" = 93fbed76-6aa6-4273-904e-d60b81e95ff9 limit 1)

**Comment by masadi** [comment]
Silahkan lakukan pull ulang, kemudian jalankan di command prompt:
```composer update```
```php artisan config:cache```
```php artisan erapor:update```
