### ISSUE TITLE
Port Postgrsql berubah?

### ISSUE THREAD

**Issue by matthelosh** [eraporsmk/eraporsmk#27]
Apakah port untuk database nya memang dirubah menjadi 58154?

Illuminate\Database\QueryException thrown with message "SQLSTATE[08006] [7] could not connect to server: Connection refused
    Is the server running on host "localhost" (::1) and accepting
    TCP/IP connections on port 58154?
could not connect to server: Connection refused
    Is the server running on host "localhost" (127.0.0.1) and accepting
    TCP/IP connections on port 58154? (SQL: select * from "ref"."tahun_ajaran" where "periode_aktif" = 1 order by "tahun_ajaran_id" desc)"

**Comment by matthelosh** [comment]
Setelah saya ganti port postgres, muncul error. di file .env suah sesuai dengan username yang dibuat untuk erapor

SQLSTATE[08006] [7] FATAL: password authentication failed for user "postgres" FATAL: password authentication failed for user "postgres" (SQL: select * from "ref"."tahun_ajaran" where "periode_aktif" = 1 order by "tahun_ajaran_id" desc)

**Comment by eraporsmk** [comment]
silahkan lakukan git pull origin master kembali

**Comment by febrimipu** [comment]
> 
> 
> Setelah saya ganti port postgres, muncul error. di file .env suah sesuai dengan username yang dibuat untuk erapor
> 
> SQLSTATE[08006] [7] FATAL: password authentication failed for user "postgres" FATAL: password authentication failed for user "postgres" (SQL: select * from "ref"."tahun_ajaran" where "periode_aktif" = 1 order by "tahun_ajaran_id" desc)


hmmm...
Coba ganti file database.php yang ada di folder config dengan database.php yang lama.
lalu coba kembali.

**Comment by muh-ramadhan** [comment]
> Setelah saya ganti port postgres, muncul error. di file .env suah sesuai dengan username yang dibuat untuk erapor
> 
> SQLSTATE[08006] [7] FATAL: password authentication failed for user "postgres" FATAL: password authentication failed for user "postgres" (SQL: select * from "ref"."tahun_ajaran" where "periode_aktif" = 1 order by "tahun_ajaran_id" desc)

Pastikan Username dan Databasenya Sudah Sesuai dengan yang anda buat dan jangan lupa di grant all
`DB_CONNECTION=pgsql
DB_HOST=localhost
DB_PORT=5432
DB_DATABASE=nama_database_yang_dibuat
DB_USERNAME=username_databasenya
DB_PASSWORD=kata_sandi_databasenya

lalu pastikan database `tahun_ajaran` sudah ada
jalankan perintah php` artisan migrate` dan `php artisan db:seed`

**Comment by dbrw** [comment]
Hal ini juga terjadi di server kami. Server postgres kami berada di mesin yang terpisah, tapi aplikasi erapor tetap menggunakan koneksi ke `localhost`. Berikut error waktu mau coba ambil data di tinker:
```
Illuminate/Database/QueryException with message 'SQLSTATE[08006] [7] could not connect to server: Connection refused
        Is the server running on host "localhost" (::1) and accepting
        TCP/IP connections on port 58154?
could not connect to server: Connection refused
        Is the server running on host "localhost" (127.0.0.1) and accepting
        TCP/IP connections on port 58154? (SQL: select * from "users" where exists (select * from "roles" inner join "role_user" on "roles"."id" = "role_user"."role_id" where "users"."user_id" = "role_user"."user_id" and "role_user"."user_type" = App/User and "name" = wali))'
```

Isi file `.env` yang berhubungan dengan DB (telah disensor):

```
DB_CONNECTION=pgsql
DB_HOST=192.168.###.###
DB_PORT=5432
DB_DATABASE=#####
DB_USERNAME=#####
DB_PASSWORD=#####
```

Saya telah melakukan:
- `git pull origin`
- checkout ke tag v.5.1.1 dari v.5.1.0
- `composer install` untuk mengupdate package
- `php artisan config:cache`

Saya tidak bisa melakukan:
- `php artisan migrate:status` (error seperti di atas)
- `php artisan erapor:update` (tidak ada respon apa-apa)

Sepertinya berkaitan dengan file `config/database.php` yang berubah dari v.5.1.0.

---

Update:

Saya coba checkout file `config/database.php` dari versi v.5.1.0 dan sekarang saya bisa lakukan perintah `php artisan migrate:status` tanpa error. Sepertinya di file tersebut ada konfigurasi untuk fitur eRapor Synchronizer seperti disebutkan di https://github.com/eraporsmk/eraporsmk/releases/tag/v.5.1.1.

Yang jadi masalah mungkin adalah bagaimana untuk menggunakan eRapor Synchronizer yang dapodiknya ada di mesin terpisah? Mungkin bisa dengan menggunakan variabel baru di file `.env` dengan memberikan contoh di file `.env.example`.

---

Update 2:

Deduksi saya di atas salah karena setelah saya telusuri lebih lanjut, yang terjadi adalah file `config/database.php` tidak menggunakan nilai dari environment variable yang diberikan pada file `.env` saya berhasil update menggunakan file `config/database.php` dari versi v.5.1.0.
