### ISSUE TITLE
Gagal Update erapor Versi 5.1.1

### ISSUE THREAD

**Issue by febrimipu** [eraporsmk/eraporsmk#31]
Proses update selalu terhenti disini. tidak ada keterangan update gagal maupun berhasil.

![image](https://user-images.githubusercontent.com/56257569/97144433-01a4a500-1797-11eb-9a6c-9a106f5c0be7.png)

**Comment by muh-ramadhan** [comment]
errornya updatenya dari erapor versi berapa?

**Comment by ariemusbandi** [comment]
> Proses update selalu terhenti disini. tidak ada keterangan update gagal maupun berhasil.
> 
> ![image](https://user-images.githubusercontent.com/56257569/97144433-01a4a500-1797-11eb-9a6c-9a106f5c0be7.png)

Saya juga mengalami hal yang sama, update dari versi 5.1.0

**Comment by eraporsmk** [comment]
Jika gagal  melakukan pembaharuan via aplikasi, silahkan dicoba lakukan pembaharuan via command prompt.
Untuk detilnya silahkan hubungi Tim Helpdesk
