### ISSUE TITLE
Erapor di belakang reverse proxy

### ISSUE THREAD

**Issue by dbrw** [eraporsmk/eraporsmk#32]
Di sekolah, kami menggunakan reverse proxy sebagai end point untuk https, saya telah mencoba melakukan configurasi trustedproxy pada file `config/trustedproxy.php` namun url yang dihasilkan oleh fungsi `asset()` pada view masih menghasilkan url dengan skema http.

Mohon petunjuk bagaimana cara agar erapor dapat ditempatkan di belakang reverse proxy dengan baik, berhubung kami ada beberapa aplikasi berbasis laravel lain yang berjalan dengan baik di belakang reverse proxy.

**Comment by masadi** [comment]
Coba running artisan:
`php artisan config:cache`

**Comment by dbrw** [comment]
Solved, Pak. Terima kasih!
