### ISSUE TITLE
Sinkronisasi Dapodik Error

### ISSUE THREAD

**Issue by muh-ramadhan** [eraporsmk/eraporsmk#33]
**PTK**
![image](https://user-images.githubusercontent.com/47452507/102442830-e26c1a80-4057-11eb-8c1b-ddc3701c745b.png)

**Peserta Didik Aktif**
![image](https://user-images.githubusercontent.com/47452507/102442878-fd3e8f00-4057-11eb-96f7-a8d5ccc3439a.png)

**Peserta Didik Keluar**
![image](https://user-images.githubusercontent.com/47452507/102442895-0af41480-4058-11eb-8850-d28094775abc.png)

**Relasi Dunia Usaha dan Industri**
![image](https://user-images.githubusercontent.com/47452507/102442961-34ad3b80-4058-11eb-858d-0aa032dd0f9d.png)

**Jurusan**
![image](https://user-images.githubusercontent.com/47452507/102442999-47c00b80-4058-11eb-96a7-5912208db925.png)

**Mata Pelajaran**
![image](https://user-images.githubusercontent.com/47452507/102443048-67573400-4058-11eb-9754-6a70ea3be2bb.png)

**Mata Pelajaran Kurikulum**
![image](https://user-images.githubusercontent.com/47452507/102443278-e0568b80-4058-11eb-962a-62ddaffdb4da.png)

**Wilayah**
![image](https://user-images.githubusercontent.com/47452507/102443293-e9475d00-4058-11eb-8719-2378bbfbab40.png)

**Ref. Kompetensi Dasar**
![image](https://user-images.githubusercontent.com/47452507/102443305-f5331f00-4058-11eb-90f1-abade14b83f5.png)

**Comment by ddiskandar** [comment]
Sinkronnya pakai eRapor SMK Synchronizer
link download : http://bit.ly/erapor-synchronizer

**Comment by muh-ramadhan** [comment]
semua datanya sudah di singkron menggunakan eRapor SMK Synchronizer gan, sepertinya ada beberapa baris kode yang harus diubah dan ditambah.
