### ISSUE TITLE
Tidak bisa register

### ISSUE THREAD

**Issue by hid0** [eraporsmk/eraporsmk#34]
tidak bisa register, padahal password sudah terisi
![image](https://user-images.githubusercontent.com/20245892/111861073-0e13df00-897e-11eb-98a5-3f92c6b45b3b.png)

**Comment by dbrw** [comment]
nggak ada penyelesaiannya, Pak?

**Comment by hid0** [comment]
ada penyelesaiannya, register menggunakan erapor-synchronizer
pastikan menggunakan versi yang terbaru🙏🏼🙏🏼
