### ISSUE TITLE
Eror tidak bisa login 419  Halaman Kedaluwarsa

### ISSUE THREAD

**Issue by imambukhori84** [eraporsmk/eraporsmk#35]
tidak bisa login 419  Halaman Kedaluwarsa. Mohon solusinya
![2021-03-24](https://user-images.githubusercontent.com/72124788/112250638-50923000-8c8c-11eb-8eca-074f47d2f945.png)

**Comment by eraporsmk** [comment]
Kembali ke halaman utama terlebih dahulu (tanpa /login)
Kemungkinan aplikasi iddle cukup lama, jadi token sudah kadaluarsa
Terima Kasih
