### ISSUE TITLE
Unparenthesized `a ? b : c ? d : e` is deprecated. Use either `(a ? b : c) ? d : e` or `a ? b : (c ? d : e)`

### ISSUE THREAD

**Issue by goesredy** [eraporsmk/eraporsmk#36]
Banyak sekali error seperti ini, sepertinya banyak conditional yg memakai shortif tanpa pengurungan.

PHP 7.4

**Comment by dbrw** [comment]
Pak @masadi apakah repo ini menerima PR?

**Comment by masadi** [comment]
> 
> 
> Banyak sekali error seperti ini, sepertinya banyak conditional yg memakai shortif tanpa pengurungan.
> 
> PHP 7.4

PHP 7.4 belum support, tested di PHP 7.2

**Comment by masadi** [comment]
> 
> 
> Pak @masadi apakah repo ini menerima PR?

Silahkan pak
