### ISSUE TITLE
Data peserta didik aktif tidak lengkap, error 405

### ISSUE THREAD

**Issue by rpl-skensa** [eraporsmk/eraporsmk#37]
Pada bagian peserta didik aktif, jika ditampilkan detil, disana ada field "Diterima dikelas" dengan tombol "refresh", yang ternyata di-response "405" oleh server yg direquest.
Metode referensi bisa saya lihat di "SinkronisasiController@diterima_dikelas", me-request ke server luar, tapi error 405 "Method not Allowed"

Bisa bantu apa solusi yg bisa saya lakukan ?

Terima kasih banyak atas bantuannya.

**Comment by eraporsmk** [comment]
Server dapodik di direktorat SMK kadang tidak bisa di akses. Silahkan isi manual saja.
Terima Kasih
