### ISSUE TITLE
Class 'App\Rombel4_tahun' not found

### ISSUE THREAD

**Issue by febrimipu** [eraporsmk/eraporsmk#38]
Setelah update e-Rapor SMK Versi 5.1.2 terdapat pesan error didirektori app/Http/Controllers/LaporanController.php

FatalThrowableError (E_ERROR)
Class 'App\Rombel4_tahun' not found

![2](https://user-images.githubusercontent.com/56257569/119315359-f4ee1e00-bc9f-11eb-867b-84f91e527359.png)

**Comment by is33p0wer** [comment]
coba edit file LaporanController.php (yang ada di direktori app/Http/Controllers/)

ganti App\Rombel4_tahun menjadi App\Rombel4_Tahun

**Comment by eraporsmk** [comment]
Sudah dirilis updater baru versi 5.1.3
Terima kasih
