### ISSUE TITLE
Tidak berhasil simpan PKL

### ISSUE THREAD

**Issue by ddiskandar** [eraporsmk/eraporsmk#42]
Versi eRaporSMK 5.1.4

tidak berhasil simpan PKL, bila melihat erornya sepertinya kurang data bidang usaha, di source code, bidang usaha diberi comment  sehingga tidak ada data yang dikirim ke LaporanController, mohon solusi

![erapor error](https://user-images.githubusercontent.com/22410705/123504063-3861f080-d681-11eb-9814-f27274eb4d9e.png)
![erapor error2](https://user-images.githubusercontent.com/22410705/123504066-39931d80-d681-11eb-983c-7013f5fed0c4.png)

**Comment by masadi** [comment]
Silahkan di update ke versi 5.1.5 via git
