### ISSUE TITLE
Tidak Bisa Registrasi menggunakan erapor syncr

### ISSUE THREAD

**Issue by smkn1krangkeng** [eraporsmk/eraporsmk#44]
Gagal registrasi padahal web service dapodik sudah dibuat

**Comment by masadi** [comment]
Tutup terlebih dahulu erapor-synchronizernya.
Buka command prompt (cmd)
Jalankan perintah berikut
`cd C:\erapor-synchronizer\www`
`git pull origin master`

Pastikan sudah terinstall aplikasi GIT di sistem operasi yang sedang dipakai.
Silahkan dicoba lagi registrasinya...
Mohon maaf, screenshot nya sebaiknya dihapus, kode registrasinya tidak di blur.

Terima kasih

**Comment by smkn1krangkeng** [comment]
ok, solved terimakasih..
