### ISSUE TITLE
Gagal kirim data ke erapor saat progress syncronize 

### ISSUE THREAD

**Issue by smkn1krangkeng** [eraporsmk/eraporsmk#45]
Gagal kirim data ke erapor saat progress syncronize 
![error2](https://user-images.githubusercontent.com/88963074/130194160-820a1d5a-2087-463c-bb09-dea8377cd451.JPG)

**Comment by smkn1krangkeng** [comment]
mohon bantuannya..

**Comment by smkn1krangkeng** [comment]
error keluar saat "Mengambil data referensi KD dari Server"

**Comment by eraporsmk** [comment]
Baik, kita periksa dulu pak...

**Comment by smkn1krangkeng** [comment]
sudah done, ternyata masalahnya adalah dapodik harus teregistasi online
