### ISSUE TITLE
ERROR 500 cetak Rapor PTS

### ISSUE THREAD

**Issue by mzdyn** [eraporsmk/eraporsmk#48]
Terdapat error 500 pada eraporsmk ver 5.1.5 setelah tombol cetak rapor diklik, pada menu laporan hasil belajar. Sebelumnya saat selesai update ke versi 5.1.5 sempat dilakukan ujicoba cetak rapor PTS dan berhasil, tetapi kasus error ini terjadi setelah semua guru membuat perencanaan dan penilaian. Mohon solusi permasalahan tersebut

**Comment by dbrw** [comment]
biasanya ada stack trace-nya di folder storage/logs, Pak.

**Comment by mzdyn** [comment]
[laravel 13-10-2021.txt](https://github.com/eraporsmk/eraporsmk/files/7335454/laravel.13-10-2021.txt)

**Comment by masadi** [comment]
https://seputar.erapor-smk.net/2021/10/15/error-500-saat-cetak-rapor-uts/
https://github.com/mpdf/mpdf/issues/1392
