### ISSUE TITLE
Error Sinkronasi Ambil Data Dapodik (Online)

### ISSUE THREAD

**Issue by muh-ramadhan** [eraporsmk/eraporsmk#49]
**SQL error 1 : jenjang_pendidikan_id**
ERROR:  numeric field overflow
DETAIL:  A field with precision 1, scale 0 must round to an absolute value less than 10^1.

**SQL error 2 : jurusan_induk**
ERROR:  insert or update on table "jurusan" violates foreign key constraint "ref_jurusan_jurusan_induk_foreign"
DETAIL:  Key (jurusan_induk)=(?) is not present in table "jurusan".

```
In statement:
INSERT INTO "ref"."jurusan"("jurusan_id","nama_jurusan","nama_jurusan_en","untuk_sma","untuk_smk","untuk_pt","untuk_slb","untuk_smklb","jenjang_pendidikan_id","jurusan_induk","level_bidang_id","created_at","updated_at","deleted_at","last_sync")VALUES ('KRS001','Kursus','','0','0','0','0','0','90','?','-','2016-07-01 11:23:59','2016-07-31 15:10:36','2016-07-31 15:10:36','2016-07-01 11:23:59.903')
```

![image](https://user-images.githubusercontent.com/47452507/144741497-2ba34080-be17-4af3-844c-ef1607f8ec26.png)

**FIX error :**

```
INSERT INTO "ref"."jurusan"("jurusan_id","nama_jurusan","nama_jurusan_en","untuk_sma","untuk_smk","untuk_pt","untuk_slb","untuk_smklb","jenjang_pendidikan_id","jurusan_induk","level_bidang_id","created_at","updated_at","deleted_at","last_sync")VALUES ('KRS001','Kursus','','0','0','0','0','0','0','NULL','-','2016-07-01 11:23:59','2016-07-31 15:10:36','2016-07-31 15:10:36','2016-07-01 11:23:59.903')
```

**Comment by muh-ramadhan** [comment]
Error ini juga muncul karena kolom jenjang_pendidikan_id=90
sedangkan jenjang_pendidikan_id bernilai numeric 1,0

![image](https://user-images.githubusercontent.com/47452507/144742374-b5234ea2-46c7-4470-9865-6052a10e7528.png)

**Comment by muh-ramadhan** [comment]
jenjang_pendidikan_id typenya di rubah jadi character varying(25), atau opsi lain min, mohon bantuannya. atau mungkin bisa untuk next update

**Comment by masadi** [comment]
sudah diganti menjadi numeric 2,0
