### ISSUE TITLE
IonCibe telah diinstal tapi tidak bisa

### ISSUE THREAD

**Issue by xeizer** [eraporsmk/eraporsmk#5]
![ioncuber OK](https://user-images.githubusercontent.com/33388453/71567465-f38fe480-2af1-11ea-94fd-12a8a6a3bc53.png)
ini ioncuber sudah ada, tetapi pasa saat php artisna key:generate gak bisa
![ioncube gak detek](https://user-images.githubusercontent.com/33388453/71567483-13bfa380-2af2-11ea-9252-a89185b62d5f.png)

**Comment by xtrynt** [comment]
Testing dulu pakai phpinfo();

**Comment by gurumutant** [comment]
> ![ioncuber OK](https://user-images.githubusercontent.com/33388453/71567465-f38fe480-2af1-11ea-94fd-12a8a6a3bc53.png)
> ini ioncuber sudah ada, tetapi pasa saat php artisna key:generate gak bisa
> ![ioncube gak detek](https://user-images.githubusercontent.com/33388453/71567483-13bfa380-2af2-11ea-9252-a89185b62d5f.png)

Pastikan setting extension utk ioncube juga ditambahkan di php.ini utk CLI, tidak hanya yg apache. Sesuai tutorial di seputar.erapor-smk.net
