### ISSUE TITLE
Update ke Laravel 7.x

### ISSUE THREAD

**Issue by xeizer** [eraporsmk/eraporsmk#7]
Apa ada kemungkinan update laravelnya ?

**Comment by eraporsmk** [comment]
@xeizer untuk saat ini belum ada rencana untuk upgrade ke laravel 7 pak, mungkin nanti kalo pakai laravel 7 perlu bundle installer baru, agar pengguna tinggal pakai

**Comment by dbrw** [comment]
Sepertinya lebih baik pakai versi LTS, Pak. supaya developer nggak perlu uber-uberan dengan versi laravel-nya dan bisa fokus ke bugfix dan feature.

**Comment by eraporsmk** [comment]
jika ada yang mencoba erapor menggunakan Laravel7, silahkan memakai branch review.
terima kasih
