### ISSUE TITLE
sinkronisasi Gagal terus

### ISSUE THREAD

**Issue by xeizer** [eraporsmk/eraporsmk#9]
![Screenshot_1](https://user-images.githubusercontent.com/33388453/79938494-f50d6000-8486-11ea-80eb-00e432a60446.png)

proses singkronisasi yang gagal terus apa dari server dapodik atau dari sisi lokal ya ?

**Comment by eraporsmk** [comment]
dari server dapodik, kemungkinan server sedang padat.
